model:
  _target_: fdlsar.models.mae_segmentation.MaskedAutoEncoder_Segmentation
  num_channels: 12
  decoder_type: deconv
  backbone:
    _target_: fdlsar.models.components.checkpoint.ModelFromHydraRun
    hydra_run_path:  ${checkpoint_folder_path}/${checkpoint_name}
    model_expression: backbone
    freeze: False
    enable_loading_weights: True
