dataloader:
  _target_: fdlsar.datamodules.mergedmulti_datamodule.MergedMultiDataModule

  datasets_spec:
    gunw_short:
      class:  fdlsar.datamodules.components.gunw_blosc.GUNWDataset
      skip_constant_channels: False
      kwargs:
        year:  2020
        variable: 'unwrappedPhase'
        normalize: True
        min_days: 0
        max_days: 60
        selection_rule: 'far'

    gunw_medium:
      class:  fdlsar.datamodules.components.gunw_blosc.GUNWDataset
      skip_constant_channels: False
      kwargs:
        year:  2020
        variable: 'unwrappedPhase'
        normalize: True
        min_days: 72
        max_days: 132
        selection_rule: 'far'

    gunw_long:
      class:  fdlsar.datamodules.components.gunw_blosc.GUNWDataset
      skip_constant_channels: False
      kwargs:
        year:  2020
        variable: 'unwrappedPhase'
        normalize: True
        min_days: 140
        max_days: 216
        selection_rule: 'far'

    agb:
      class: fdlsar.datamodules.components.biomass_blosc.BiomassDataset
      skip_constant_channels: False
      kwargs:
        year: 2020

  transforms:
    gunw_short:
      _target_: fdlsar.datamodules.transforms.GUNWTransform
      key: gunw_short
    gunw_medium:
      _target_: fdlsar.datamodules.transforms.GUNWTransform
      key: gunw_medium
    gunw_long:
      _target_: fdlsar.datamodules.transforms.GUNWTransform
      key: gunw_long
    agb:
       _target_: fdlsar.datamodules.transforms.BiomassTransform
       size: (45, 55)
       preserve: mean

  split_files:
    - ${dataset_path}/china/china_partitions_aschips_23489d30a312b_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/conus/conus_partitions_aschips_293d95e3ee589_splits_60bands_angle09_60-20-20.csv
    - ${dataset_path}/middleeast/middleeast_partitions_aschips_0a596e5469add_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/pakin/pakin_partitions_aschips_0f26dc7030c75_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/southamerica/southamerica_partitions_aschips_3219aa0f411c2_splits_60bands_angle02_60-20-20.csv

  num_workers: 12
  batch_size: 8
  prefetch_factor: 1
  limit_pct_train: 1.0
  limit_pct_val: 1.0
  limit_pct_test: 1.0
  pin_memory: True
