dataloader:
  _target_: fdlsar.datamodules.mergedmulti_datamodule.MergedMultiDataModule

  datasets_spec:
    gssic:
      class: fdlsar.datamodules.components.gssic.GSSICDataset
      # class: fdlsar.datamodules.components.gssic_blosc.GSSICDataset
      kwargs:
        variable:    ['coherence']
        season:      ['winter', 'spring', 'summer', 'fall']
        polarimetry: ['vv', 'vh'] #N.B this doesn't actually do anything for coherence but needs to be filled in
        deltadays:   [36] #[12 24 36 48] - check this is sensible
        normalize:   True
      skip_constant_channels: True

    esawc:
      class: fdlsar.datamodules.components.esawc.ESAWCDataset
      # class: fdlsar.datamodules.components.esawc_blosc.ESAWCDataset
      kwargs:
        year: 2020
      skip_constant_channels: False

  transforms:
    gssic:
      _target_: fdlsar.datamodules.transforms.GSSICTransform

  split_files:
    - ${dataset_path}/china/china_partitions_aschips_23489d30a312b_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/conus/conus_partitions_aschips_293d95e3ee589_splits_60bands_angle09_60-20-20.csv
    - ${dataset_path}/middleeast/middleeast_partitions_aschips_0a596e5469add_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/pakin/pakin_partitions_aschips_0f26dc7030c75_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/southamerica/southamerica_partitions_aschips_3219aa0f411c2_splits_60bands_angle02_60-20-20.csv

  num_workers: 12
  batch_size: 8
  prefetch_factor: 1
  limit_pct_train: 1.
  pin_memory: True
