dataloader:
  _target_: fdlsar.datamodules.mergedmulti_datamodule.MergedMultiDataModule

  datasets_spec:
    s2rgbm:
      class: fdlsar.datamodules.components.s2rgbm.S2rgbmDataset
      # class: fdlsar.datamodules.components.s2rgbm_blosc.S2rgbmDataset
      skip_constant_channels: False
      kwargs:
        year:              2020
        months:            ['03', '06', '09', '12']
        normalize:         True

    ghsbuilts:
      class: fdlsar.datamodules.components.ghsbuilts.GHSBuiltSDataset
      # class: fdlsar.datamodules.components.ghsbuilts_blosc.GHSBuiltSDataset
      skip_constant_channels: False
      kwargs:
        year: 2020

  split_files:
    - ${dataset_path}/china/china_partitions_aschips_23489d30a312b_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/conus/conus_partitions_aschips_293d95e3ee589_splits_60bands_angle09_60-20-20.csv
    - ${dataset_path}/middleeast/middleeast_partitions_aschips_0a596e5469add_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/pakin/pakin_partitions_aschips_0f26dc7030c75_splits_60bands_angle15_60-20-20.csv
    - ${dataset_path}/southamerica/southamerica_partitions_aschips_3219aa0f411c2_splits_60bands_angle02_60-20-20.csv

  transforms:
    s2rgbm:
       _target_: fdlsar.datamodules.transforms.S2rgbmTransform
    ghsbuilts:
       _target_: fdlsar.datamodules.transforms.GhsBuiltSTransform
       size: (45, 55)
       preserve: mean

  num_workers: 12
  batch_size: 8
  prefetch_factor: 1
  limit_pct_train: 1.
  pin_memory: True
